CREATE TABLE `bulk_onboarding_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobName` varchar(255) NOT NULL,
	`source` enum('csv_import','api_batch','manual_entry','agent') NOT NULL DEFAULT 'csv_import',
	`totalRecords` int NOT NULL,
	`processedRecords` int DEFAULT 0,
	`successCount` int DEFAULT 0,
	`failureCount` int DEFAULT 0,
	`skippedCount` int DEFAULT 0,
	`status` enum('pending','processing','completed','failed','cancelled') NOT NULL DEFAULT 'pending',
	`errorLog` json,
	`generatedBpans` json,
	`autoGenerateBpan` boolean DEFAULT true,
	`registerWarranty` boolean DEFAULT false,
	`defaultWarrantyMonths` int,
	`createdById` int NOT NULL,
	`csvFileUrl` text,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bulk_onboarding_jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `warranty_claims` (
	`id` int AUTO_INCREMENT NOT NULL,
	`warrantyId` int NOT NULL,
	`batteryId` int NOT NULL,
	`bpan` varchar(21) NOT NULL,
	`claimType` enum('defect','performance_degradation','physical_damage','thermal_event','capacity_loss','premature_failure','other') NOT NULL,
	`description` text NOT NULL,
	`evidenceUrls` json,
	`sohAtClaim` decimal(5,2),
	`cycleCountAtClaim` int,
	`status` enum('submitted','under_review','approved','rejected','in_repair','replacement_issued','resolved','escalated') NOT NULL DEFAULT 'submitted',
	`assignedTo` varchar(255),
	`resolutionType` enum('replacement','repair','refund','pro_rata_credit','rejected','pending') DEFAULT 'pending',
	`resolutionNotes` text,
	`resolutionDate` timestamp,
	`claimedById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `warranty_claims_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `warranty_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batteryId` int NOT NULL,
	`bpan` varchar(21) NOT NULL,
	`serialNumber` varchar(100),
	`modelNumber` varchar(100),
	`warrantyType` enum('standard','extended','premium','commercial') NOT NULL DEFAULT 'standard',
	`coverageType` enum('full_replacement','pro_rata','labor_only','parts_only','comprehensive') NOT NULL DEFAULT 'full_replacement',
	`warrantyTermMonths` int NOT NULL,
	`purchaseDate` timestamp NOT NULL,
	`warrantyStartDate` timestamp NOT NULL,
	`warrantyEndDate` timestamp NOT NULL,
	`status` enum('active','expired','voided','claimed','suspended','pending_activation') NOT NULL DEFAULT 'pending_activation',
	`customerName` varchar(255) NOT NULL,
	`customerPhone` varchar(20),
	`customerWhatsApp` varchar(20),
	`customerEmail` varchar(320),
	`customerAddress` text,
	`dealerName` varchar(255),
	`dealerCode` varchar(50),
	`dealerPhone` varchar(20),
	`dealerEmail` varchar(320),
	`invoiceNumber` varchar(100),
	`invoiceUrl` text,
	`purchaseAmount` decimal(12,2),
	`purchaseCurrency` varchar(10) DEFAULT 'INR',
	`manufacturer` varchar(255),
	`totalClaims` int DEFAULT 0,
	`lastClaimDate` timestamp,
	`notes` text,
	`metadata` json,
	`registeredById` int NOT NULL,
	`activatedAt` timestamp,
	`voidedAt` timestamp,
	`voidReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `warranty_records_id` PRIMARY KEY(`id`)
);
